### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by GnubiBORED** [shroudedcode/apk-mitm#19]
First i will upload the apk
https://www.virustotal.com/gui/file/d2fd0492c673dba01efd106a246ec8486ada85b23b7705d24e069ee910b33c44/detection
and the link
https://mega.nz/file/hogAza4R#pbbfGAKIlkzjwRDKcS8qKQzK8bXMTtAvjoZI05rW8tE

Hello, so i basically found this for be able to see HTTPS traffic in android 7.0 and above.

Im using a Pocophone f1 with custom pixel rom. full rooted .

I downloaded and run the command.
```
npx apk-mitm test.apk

  ╭ apk-mitm v0.8.0
  ├ apktool v2.4.1
  ╰ uber-apk-signer v1.1.0

  Using temporary directory:
  C:\Users\LOCALH~1\AppData\Local\Temp\73f987887a918a71caaa00af34688d5b

  √ Downloading tools
  √ Decoding APK file
  √ Modifying app manifest
  √ Modifying network security config
  ↓ Disabling certificate pinning [skipped]
    → No certificate pinning logic found.
  √ Encoding patched APK file
  √ Signing patched APK file

   Done!  Patched file: ./test-patched.apk


```

after this i installed the patched apk via adb

```
adb install Tribal-patched.apk
Performing Streamed Install
Success
```

But when running and trying to debugging HTTPS traffic im getting.

**java.security.cert.CertPathValidatorException: Trust anchor for certification path not found**

_**The app needs to have certificate pinning cause witouth any mitm it works good(im using charles if that matters)**_

**Comment by GnubiBORED** [comment]
I decompile it with jadx seems they are using **X509Certificate**  checkClientTrusted

in com.adjust.sdk.AdjustFactory class in  useTestConnectionOptions()
`public static void useTestConnectionOptions() {
        connectionOptions = new UtilNetworking.IConnectionOptions() {
            public void applyConnectionOptions(HttpsURLConnection httpsURLConnection, String str) {
                new UtilNetworking.ConnectionOptions().applyConnectionOptions(httpsURLConnection, str);
                try {
                    SSLContext instance = SSLContext.getInstance("TLS");
                    instance.init((KeyManager[]) null, new TrustManager[]{new X509TrustManager() {
                        public void checkClientTrusted(X509Certificate[] x509CertificateArr, String str) {
                            AdjustFactory.getLogger().verbose("checkClientTrusted ", new Object[0]);
                        }

                        public void checkServerTrusted(X509Certificate[] x509CertificateArr, String str) {
                            AdjustFactory.getLogger().verbose("checkServerTrusted ", new Object[0]);
                            try {
                                if (!AdjustFactory.byte2HexFormatted(MessageDigest.getInstance("SHA1").digest(x509CertificateArr[0].getEncoded())).equalsIgnoreCase("7BCFF44099A35BC093BB48C5A6B9A516CDFDA0D1")) {
                                    throw new CertificateException();
                                }
                            } catch (NoSuchAlgorithmException e2) {
                                AdjustFactory.getLogger().error("testingMode error %s", e2.getMessage());
                            } catch (CertificateEncodingException e3) {
                                AdjustFactory.getLogger().error("testingMode error %s", e3.getMessage());
                            }
                        }

                        public X509Certificate[] getAcceptedIssuers() {
                            AdjustFactory.getLogger().verbose("getAcceptedIssuers", new Object[0]);
                            return null;
                        }
                    }}, new SecureRandom());
                    httpsURLConnection.setSSLSocketFactory(instance.getSocketFactory());
                    httpsURLConnection.setHostnameVerifier(new HostnameVerifier() {
                        public boolean verify(String str, SSLSession sSLSession) {
                            AdjustFactory.getLogger().verbose("verify hostname ", new Object[0]);
                            return true;
                        }
                    });
                } catch (Exception e2) {
                    AdjustFactory.getLogger().error("testingMode error %s", e2.getMessage());
                }
            }
        };
    }
}`

**Comment by shroudedcode** [comment]
> The app needs to have certificate pinning cause witouth any mitm it works good

Yeah, certificate pinning certainly is the issue here.

> I decompile it with jadx seems they are using **X509Certificate** checkClientTrusted
> 
> in com.adjust.sdk.AdjustFactory class in useTestConnectionOptions()

That's true, but that piece of code in particular shouldn't be an issue because it's not or just very lightly obfuscated. `apk-mitm` shouldn't have any issues finding this code and disabling it. See the [list of supported method signatures](https://github.com/shroudedcode/apk-mitm/blob/a64794b927359469bfb9cb473e02505438d77a25/src/tasks/disable-certificate-pinning.ts#L10-L15)  for more details (note that these are in Smali instead of Java).

I searched the Smali code (you can find it in the temporary folder `apk-mitm` creates for each APK) for more `X509Certificate`-related methods using a [VS Code search editor](https://code.visualstudio.com/updates/v1_43#_search-editors) and found some interesting things: There are a few obvious methods (like the ones you found in `com.adjust.sdk`) and then there are others that have similar signatures (similar argument and return types) but with very short names (like `a`, `b`, `c`):

```yml
# The obvious ones
decode/smali/com/adjust/sdk/AdjustFactory$1$1.smali:
   37: .method public checkClientTrusted([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V
   56: .method public checkServerTrusted([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V
  157: .method public getAcceptedIssuers()[Ljava/security/cert/X509Certificate;

# The less obvious ones
decode/smali/j/a/a/a/n/e/a.smali:
   7: .method private static a(Ljava/security/cert/X509Certificate;Ljava/security/cert/X509Certificate;)Z
  46: .method public static a([Ljava/security/cert/X509Certificate;Lj/a/a/a/n/e/i;)[Ljava/security/cert/X509Certificate;

decode/smali/j/a/a/a/n/e/h.smali:
  117: .method private a([Ljava/security/cert/X509Certificate;)V
  229: .method private a([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V
  255: .method private a(Ljava/security/cert/X509Certificate;)Z

decode/smali/j/a/a/a/n/e/i.smali:
  200: .method public a(Ljava/security/cert/X509Certificate;)Ljava/security/cert/X509Certificate;
  254: .method public b(Ljava/security/cert/X509Certificate;)Z

decode/smali/o/g.smali:
  115: .method static a(Ljava/security/cert/X509Certificate;)Lp/f;
  137: .method static b(Ljava/security/cert/X509Certificate;)Lp/f;

decode/smali/o/h0/k/a$b.smali:
  41: .method public a(Ljava/security/cert/X509Certificate;)Ljava/security/cert/X509Certificate;

decode/smali/o/h0/m/a.smali:
  21: .method private a(Ljava/security/cert/X509Certificate;Ljava/security/cert/X509Certificate;)Z

decode/smali/o/h0/m/b.smali:
  24: .method public varargs constructor <init>([Ljava/security/cert/X509Certificate;)V
  81: .method public a(Ljava/security/cert/X509Certificate;)Ljava/security/cert/X509Certificate;

decode/smali/o/h0/m/d.smali:
   34: .method public static a(Ljava/security/cert/X509Certificate;)Ljava/util/List;
   80: .method private static a(Ljava/security/cert/X509Certificate;I)Ljava/util/List;
  188: .method private b(Ljava/lang/String;Ljava/security/cert/X509Certificate;)Z
  236: .method private c(Ljava/lang/String;Ljava/security/cert/X509Certificate;)Z
  487: .method public a(Ljava/lang/String;Ljava/security/cert/X509Certificate;)Z

decode/smali/o/h0/m/e.smali:
  7: .method public abstract a(Ljava/security/cert/X509Certificate;)Ljava/security/cert/X509Certificate;
```

My guess is that the short methods have the same purpose as the regular ones, but since `apk-mitm` doesn't spot them because they're obfuscated, it doesn't insert the `return-void` statements it normally uses to disable them. I don't have more time to investigate this today, but that's all I have so far. I'll probably look into this more tomorrow.

**Comment by shroudedcode** [comment]
Sorry for the late reply, but while I did actually look into the issue more on Tuesday, I didn't make enough progress to let you know (the obfuscated methods didn't lead me anywhere useful) and yesterday I just didn't have time. I was about to do some more research until I realized that maybe you could simply try a different approach instead of using `apk-mitm`...

### Using a root-specific tool

> Im using a Pocophone f1 with custom pixel rom. full **rooted** .

I only realized that you mentioned this now, but with a rooted device you might not need to edit the APK with a tool like `apk-mitm` at all. Instead, you could use something like [JustTrustMe](https://github.com/Fuzion24/JustTrustMe) which disables certificate pinning at runtime. Note that this method is quite a bit more "dangerous" than using `apk-mitm` because it requires Xposed which can cause issues on some ROMs and devices (if you don't have it installed already, that is), but it might be worth a shot.

### Inspecting the browser version

Unless you have a specific reason to look at the Android app in particular, you might also be able to look at the traffic of the [browser version of this game](https://www.tribalwars.net/en-us/) using the developer tools of your browser to find out what you want to find out. I can't tell you if this will work (maybe they're somehow hiding the requests through an encrypted WebSocket or something like that), but it can't hurt to try.

Let me know if one of these solutions works for you!

**Comment by GnubiBORED** [comment]
Gonna try with JustTrustMe but i cannot try with browser version, there are 2 apis in this game, one is browser the other one is game, i have access to game api, every bot now is being developed at browser level so i want to make one at api level cause i am one of the few that has acces to the api, or now how to get it(isnt hard but people are lazy)

I will reply in some hours, thanks for all the help 👍

**Comment by shroudedcode** [comment]
@GnubiBORED Have you found a solution yet?

**Comment by shroudedcode** [comment]
I'm closing this issue due to lack of a response.
