### ISSUE TITLE
Fails on encoding (building resources part)

### ISSUE THREAD

**Issue by takeerdevs** [shroudedcode/apk-mitm#25]
Please try latest Instagram or TikTok app and see if you succeed.
![Screenshot 2020-10-19 at 12 44 30](https://user-images.githubusercontent.com/49426357/96429200-59786480-1209-11eb-9b5f-c4a444c70394.png)

My Environment
Mac 10.15.7
  ╭ apk-mitm v0.9.0
  ├ apktool v2.4.1
  ╰ uber-apk-signer v1.1.0

Thanks.

**Comment by iashris** [comment]
hey how did you solve this?

**Comment by anilatx** [comment]
Same error is present in 0.9.1, but it seems that next apktool release should fix it: 
iBotPeaches commented 2 days ago: "Closing as solved in upcoming release." @ https://github.com/iBotPeaches/Apktool/issues/2271

**Comment by shroudedcode** [comment]
@anilatx The issue you linked to is not related to this one. `brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1)` is basically outputted for every single Apktool error, only what comes _before that_ (this wasn't even included in the first comment of that issue) matters.

This issue is more relevant: https://github.com/iBotPeaches/Apktool/issues/1927
Connor accidentally closed it as a duplicate of another issue, but [I don't think is](https://github.com/iBotPeaches/Apktool/issues/1927#issuecomment-735707169).
