### ISSUE TITLE
Struck at disabling certificate pinning step for 48 hours

### ISSUE THREAD

**Issue by tathastu871** [shroudedcode/apk-mitm#30]

**Comment by shroudedcode** [comment]
Could you please try again with the latest release? I've changed the relevant code a little bit and added better error handling, so that some errors that might've previously been silent should now be displayed. Note that this step shouldn't take more than a couple of minutes at max, so there's no need to keep `apk-mitm` running for multiple hours. Please just cancel it in that case.

Also, please provide the following details:

- your Node.js version (output of `node -v`)
- your operating system (and OS version)
- your processor architecture (e.g. 64bit)

**Comment by shroudedcode** [comment]
Closing this due to lack of a response. If anyone else encounters this same issue (it does seem to occur from time to time), please don't hesitate to comment here (make sure to include the details mentioned [above](https://github.com/shroudedcode/apk-mitm/issues/30#issuecomment-753516825)).
