### ISSUE TITLE
TypeError: contents.matchAll is not a function

### ISSUE THREAD

**Issue by RandomJoe43576** [shroudedcode/apk-mitm#38]
Im trying to patch the Lidl Plus App [https://play.google.com/store/apps/details?id=com.lidl.eci.lidlplus&hl=de&gl=US](url)
I pulled the App from my Genymotion through ADB (.\adb.exe pull /data/app/com.lidl.eci.lidlplus-1/base.apk)
![PXLUFei4VG](https://user-images.githubusercontent.com/72115079/106609854-5447e700-6566-11eb-8db4-95418bd9787d.png)

Logfiles:
![NMpH9N3KMP](https://user-images.githubusercontent.com/72115079/106609938-6f1a5b80-6566-11eb-8d03-2edb28975b80.png)

Any idea how to fix it?

**Comment by shroudedcode** [comment]
Whoops, this issue occurs because I accidentally used a feature that's only available starting in Node.js 12 without updating the README to explain that requirement, my bad! :sweat_smile: I'll make sure to fix that, but in the meantime you can just update Node.js. The current LTS release is 14, so I'd recommend [updating to that](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions) (make sure to uninstall the old version before doing that).

**Comment by RandomJoe43576** [comment]
Issue can be closed from my side. After upgrading to Node.js 15 its working.
Thank you for your help and your awesome tool!
