### ISSUE TITLE
Disabling certificate pinning       → contents.matchAll is not a function

### ISSUE THREAD

**Issue by catmobil5** [shroudedcode/apk-mitm#43]
```
  ╭ apk-mitm v0.11.1
  ├ apktool v2.5.0
  ╰ uber-apk-signer v1.2.1
  
  Using temporary directory:
  /tmp/apk-mitm-de00bd5101216addae0234f5e2d63d22

  ✔ Downloading tools
  ✔ Decoding APK file
  ❯ Applying patches
    ✔ Modifying app manifest
    ✔ Replacing network security config
    ✖ Disabling certificate pinning
      → contents.matchAll is not a function
    Encoding patched APK file
    Signing patched APK file

   Failed!  An error occurred:

TypeError: contents.matchAll is not a function
    at Object.parseSmaliHead [as default] (/usr/local/lib/node_modules/apk-mitm/dist/tasks/smali/parse-head.js:14:41)
    at Object.processSmaliFile [as default] (/usr/local/lib/node_modules/apk-mitm/dist/tasks/smali/process-file.js:20:43)

  The full logs of all commands are available here:
  /tmp/apk-mitm-de00bd5101216addae0234f5e2d63d22/logs
```

**Comment by williamtran29** [comment]
yeah, I have the same issue

**Comment by shroudedcode** [comment]
This is what happens when you [fix an issue](https://github.com/shroudedcode/apk-mitm/commit/46b683f4d2a203a532f5b54e65f1ffdf7e5fd712), but don't release a new version with it. :sweat_smile:
Anyway, [a new version with the fix](https://github.com/shroudedcode/apk-mitm/releases/tag/v0.12.0) is out now. Updating to that should get rid of the error.

_By the way: This issue only happened under Node.js 10 (which I'm only still supporting because I didn't do a major release yet). Node.js 10 will [stop receiving security patches next month](https://nodejs.org/en/about/releases/), so I generally recommend updating to Node.js 14._
