### ISSUE TITLE
MANIFEST_MALFORMED after apk-mitm possibly due to apktool

### ISSUE THREAD

**Issue by KrishnaST** [shroudedcode/apk-mitm#60]
Received malformed manifest error.
```
adb install-multiple base.apk config.en.apk
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl189496064.tmp/base.apk (at Binary XML file line #80): <meta-data> requires an android:value or android:resource attribute]
```
after some investigation 

1. Manifest Before APK-MITM
![image](https://user-images.githubusercontent.com/9427954/125159774-1e530280-e197-11eb-9425-657d153fb2b7.png)
2.  Manifest After APK-MITM
![image](https://user-images.githubusercontent.com/9427954/125159727-c3b9a680-e196-11eb-8ca9-5b0d1822b7b3.png)

**Comment by shroudedcode** [comment]
`apk-mitm` only applies patches specific to HTTPS inspection, all decoding and re-encoding of the resources within the APK is (as you might have already realized) performed by [Apktool](https://github.com/iBotPeaches/Apktool), so you'd have to check their issues. _However_, the issue here is probably the fact that the app consists of multiple APKs which are _not_ patched together. `apk-mitm` only patches the base APK which means that resources contained in the other APKs cannot be resolved by Apktool resulting in the `APKTOOL_DUMMY` value.

In order to fix this you could check if the app is also available as a single APK or if you can merge all the APKs into a single one that you could then patch. I can't really think of another solution.
