### ISSUE TITLE
Partial success....

### ISSUE THREAD

**Issue by LelandSindt** [shroudedcode/apk-mitm#69]
While trying to inspect some call made by the Tesla Android app, I am seeing what I will call partial success... That is.. some calls are visible from mitmproxy but others fail/are not visible. 

<insert this is not my area of expertise, any help you can provide would be greatly appreciated statement here.>

Can you provide any insights as to where I should look to understand why some of the calls are working/un-pinned but others continue to fail after patching?

**Comment by shroudedcode** [comment]
There are multiple ways to implement certificate pinning in Android apps and some of them (like the Network Security Config or implementations of the `X509TrustManager` interface) `apk-mitm` can patch 100% of the time because they can be detected based on simple rules. Others involve entirely custom logic to essentially perform a `certificate == pinnedCertificate` check. This logic is often part of libraries (like the popular Java HTTP client [OkHttp](https://square.github.io/okhttp/)) and detecting it reliably can be tricky. `apk-mitm` does include support for different OkHttp versions for example, but [if the library code is obfuscated](https://github.com/shroudedcode/apk-mitm/issues/59), then even those detections don't work anymore.

So, if you really want to disable certificate pinning for the affected parts of the app (note that those requests might belong to analytics tools and be less interesting anyway), you'll have to look into actually modifying the app's source code. This can be a bit of a rabbit hole to go down, but here are some links that might help you out:

- https://github.com/shroudedcode/apk-mitm#making-manual-changes
  - https://github.com/APKLab/APKLab#apply-mitm-patch
- https://medium.com/@felipecsl/bypassing-certificate-pinning-on-android-for-fun-and-profit-1b0d14beab2b
- https://levelup.gitconnected.com/bypassing-ssl-pinning-on-android-3c82f5c51d86

**Comment by LelandSindt** [comment]
@shroudedcode Thank you for the thoughtful feedback and additional information.

**Comment by LelandSindt** [comment]
Breadcrumb.. 

In my case the  https://medium.com/@felipecsl/bypassing-certificate-pinning-on-android-for-fun-and-profit-1b0d14beab2b article was most appropriate. However, removing instructions caused the app to crash. 

so instead, I changed the pinned url(s)... 

so, the articles example goes from... 

```
const-string v1, “api.example.com”
```

to 

```
const-string v1, “none.api.example.com”
```
