### ISSUE TITLE
Does it work for tcp connections?

### ISSUE THREAD

**Issue by Anonymous2716** [shroudedcode/apk-mitm#84]
The app I want to inspect uses a TCP connection. With this tool can I  inspection TCP traffic? It's great working for HTTPS .

**Comment by shroudedcode** [comment]
I've never inspected the raw TCP traffic of an app, so I'm honestly not sure. I guess it's going to depend on the proxy you're using and whether it can show and decrypt encrypted TCP traffic (if it even is encrypted). The classic HTTP proxies (like [Charles](https://www.charlesproxy.com/) and [HTTP Toolkit](https://httptoolkit.tech/)) aren't able to do this, so you might have to look into more "low-level" traffic interception tools like [Wireshark](https://www.wireshark.org/).

In any case, `apk-mitm` probably won't have anything to do with whether this is possible or not _unless_ the app also uses regular TLS for its TCP connection and fails to connect because of certificate-related errors.

**Comment by shroudedcode** [comment]
Sounds good! I'm closing this issue for now, but feel free to comment if you think there's a way that `apk-mitm` could help here.
